## Preprocessing

In [20]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import numpy as np

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [21]:
# Drop the non-beneficial ID columns, 'EIN'
application_df = application_df.drop(columns=['EIN'])

In [22]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
unique_values

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [24]:
# Look at NAME value counts to identify and replace with "Other"
application_type_counts = application_df['NAME'].value_counts()
application_type_counts

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [25]:
# Choose a cutoff value for considering categories as "Other"
cutoff_value = 5

categories_to_replace = application_type_counts[application_type_counts <=cutoff_value].index.tolist()
application_df['NAME'].replace(categories_to_replace, 'Other', inplace=True)
print(application_df['NAME'].value_counts())

NAME
Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: count, Length: 355, dtype: int64

In [26]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [27]:
# Choose a cutoff value (e.g., 1000) for considering categories as "Other"
cutoff_value = 500

categories_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()
application_df['APPLICATION_TYPE'].replace(categories_to_replace, 'Other', inplace=True)
print(application_df['APPLICATION_TYPE'].value_counts())

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [28]:
# Look at the value counts of 'CLASSIFICATION' column
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [29]:
# Filter the value counts of 'CLASSIFICATION' column for categories with counts greater than 1
filtered_classification_counts = classification_counts[classification_counts > 1]
print(filtered_classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [31]:
# Determine the cutoff value
classification_counts = application_df['CLASSIFICATION'].value_counts()
cutoff_value = 1000

# Create a list of classifications to be replaced with "Other"
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace less frequent classifications with "Other" in the 'CLASSIFICATION' column
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")
print(application_df['CLASSIFICATION'].value_counts())

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [32]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df)
application_df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [33]:
X = application_df_encoded.drop('IS_SUCCESSFUL', axis=1).values
y = application_df_encoded['IS_SUCCESSFUL'].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (27439, 398)
X_test shape: (6860, 398)
y_train shape: (27439,)
y_test shape: (6860,)

In [34]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [35]:
import tensorflow as tf

# Assume X_train is already defined and preprocessed
input_shape = len(X_train[0])

# Define the model
nn = tf.keras.models.Sequential()

# layer
nn.add(tf.keras.layers.Dense(units=100, activation='relu', input_dim=input_shape))
nn.add(tf.keras.layers.Dense(units=80, activation='sigmoid'))
nn.add(tf.keras.layers.Dense(units=30, activation='sigmoid'))
nn.add(tf.keras.layers.Dense(units=20, activation='sigmoid'))
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 100)               39900

 dense_6 (Dense)             (None, 80)                8080

 dense_7 (Dense)             (None, 30)                2430

 dense_8 (Dense)             (None, 20)                620

 dense_9 (Dense)             (None, 1)                 21

=================================================================
Total params: 51051 (199.42 KB)
Trainable params: 51051 (199.42 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [36]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [37]:
# Train the model
history = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
858/858 [==============================] - 4s 3ms/step - loss: 0.4934 - accuracy: 0.7677
Epoch 2/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4378 - accuracy: 0.7945
Epoch 3/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4297 - accuracy: 0.7970
Epoch 4/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4254 - accuracy: 0.7983
Epoch 5/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4232 - accuracy: 0.7985
Epoch 6/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4211 - accuracy: 0.7997
Epoch 7/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4197 - accuracy: 0.7996
Epoch 8/100
858/858 [==============================] - 4s 5ms/step - loss: 0.4189 - accuracy: 0.7990
Epoch 9/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4187 - accuracy: 0.8004
Epoch 10/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4174 - accuracy: 0.8010
Epoch 11/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4166 - accuracy: 0.8012
Epoch 12/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4159 - accuracy: 0.8017
Epoch 13/100
858/858 [==============================] - 4s 5ms/step - loss: 0.4153 - accuracy: 0.8008
Epoch 14/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4147 - accuracy: 0.8016
Epoch 15/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4140 - accuracy: 0.8026
Epoch 16/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4136 - accuracy: 0.8015
Epoch 17/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4133 - accuracy: 0.8015
Epoch 18/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4124 - accuracy: 0.8030
Epoch 19/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4122 - accuracy: 0.8026
Epoch 20/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4115 - accuracy: 0.8029
Epoch 21/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4112 - accuracy: 0.8032
Epoch 22/100
858/858 [==============================] - 2s 2ms/step - loss: 0.4104 - accuracy: 0.8041
Epoch 23/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4104 - accuracy: 0.8027
Epoch 24/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4106 - accuracy: 0.8048
Epoch 25/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4097 - accuracy: 0.8037
Epoch 26/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4095 - accuracy: 0.8043
Epoch 27/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4087 - accuracy: 0.8046
Epoch 28/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4091 - accuracy: 0.8051
Epoch 29/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4082 - accuracy: 0.8043
Epoch 30/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4080 - accuracy: 0.8047
Epoch 31/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4077 - accuracy: 0.8045
Epoch 32/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4077 - accuracy: 0.8048
Epoch 33/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4072 - accuracy: 0.8055
Epoch 34/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4068 - accuracy: 0.8052
Epoch 35/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4064 - accuracy: 0.8053
Epoch 36/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4061 - accuracy: 0.8054
Epoch 37/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4060 - accuracy: 0.8062
Epoch 38/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4055 - accuracy: 0.8063
Epoch 39/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4054 - accuracy: 0.8062
Epoch 40/100
858/858 [==============================] - 4s 4ms/step - loss: 0.4055 - accuracy: 0.8053
Epoch 41/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4050 - accuracy: 0.8060
Epoch 42/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4043 - accuracy: 0.8068
Epoch 43/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4046 - accuracy: 0.8056
Epoch 44/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4041 - accuracy: 0.8073
Epoch 45/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4037 - accuracy: 0.8060
Epoch 46/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4035 - accuracy: 0.8071
Epoch 47/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4036 - accuracy: 0.8075
Epoch 48/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8068
Epoch 49/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4028 - accuracy: 0.8057
Epoch 50/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4032 - accuracy: 0.8071
Epoch 51/100
858/858 [==============================] - 4s 4ms/step - loss: 0.4027 - accuracy: 0.8070
Epoch 52/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4026 - accuracy: 0.8069
Epoch 53/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4027 - accuracy: 0.8071
Epoch 54/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4022 - accuracy: 0.8072
Epoch 55/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4022 - accuracy: 0.8078
Epoch 56/100
858/858 [==============================] - 4s 4ms/step - loss: 0.4013 - accuracy: 0.8074
Epoch 57/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4015 - accuracy: 0.8064
Epoch 58/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4019 - accuracy: 0.8071
Epoch 59/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4016 - accuracy: 0.8073
Epoch 60/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4014 - accuracy: 0.8078
Epoch 61/100
858/858 [==============================] - 3s 3ms/step - loss: 0.4011 - accuracy: 0.8074
Epoch 62/100
858/858 [==============================] - 3s 4ms/step - loss: 0.4008 - accuracy: 0.8090
Epoch 63/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4008 - accuracy: 0.8079
Epoch 64/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4004 - accuracy: 0.8089
Epoch 65/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4010 - accuracy: 0.8091
Epoch 66/100
858/858 [==============================] - 2s 3ms/step - loss: 0.4007 - accuracy: 0.8073
Epoch 67/100
858/858 [==============================] - 4s 4ms/step - loss: 0.4004 - accuracy: 0.8077
Epoch 68/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3998 - accuracy: 0.8077
Epoch 69/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3997 - accuracy: 0.8088
Epoch 70/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3995 - accuracy: 0.8080
Epoch 71/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3994 - accuracy: 0.8081
Epoch 72/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3999 - accuracy: 0.8086
Epoch 73/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3996 - accuracy: 0.8081
Epoch 74/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3996 - accuracy: 0.8086
Epoch 75/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3990 - accuracy: 0.8086
Epoch 76/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3990 - accuracy: 0.8078
Epoch 77/100
858/858 [==============================] - 4s 4ms/step - loss: 0.3990 - accuracy: 0.8092
Epoch 78/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3991 - accuracy: 0.8083
Epoch 79/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3987 - accuracy: 0.8091
Epoch 80/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3991 - accuracy: 0.8088
Epoch 81/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3991 - accuracy: 0.8086
Epoch 82/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3989 - accuracy: 0.8091
Epoch 83/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3982 - accuracy: 0.8084
Epoch 84/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3983 - accuracy: 0.8094
Epoch 85/100
858/858 [==============================] - 3s 4ms/step - loss: 0.3985 - accuracy: 0.8093
Epoch 86/100
858/858 [==============================] - 4s 4ms/step - loss: 0.3993 - accuracy: 0.8095
Epoch 87/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3992 - accuracy: 0.8088
Epoch 88/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3983 - accuracy: 0.8090
Epoch 89/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3980 - accuracy: 0.8093
Epoch 90/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3982 - accuracy: 0.8082
Epoch 91/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3980 - accuracy: 0.8088
Epoch 92/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8090
Epoch 93/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3983 - accuracy: 0.8088
Epoch 94/100
858/858 [==============================] - 3s 3ms/step - loss: 0.3983 - accuracy: 0.8096
Epoch 95/100
858/858 [==============================] - 3s 4ms/step - loss: 0.3983 - accuracy: 0.8093
Epoch 96/100
858/858 [==============================] - 4s 4ms/step - loss: 0.3980 - accuracy: 0.8097
Epoch 97/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8091
Epoch 98/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8091
Epoch 99/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8095
Epoch 100/100
858/858 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8093

In [38]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 1s - loss: 0.4775 - accuracy: 0.7851 - 523ms/epoch - 2ms/step
Loss: 0.4775082468986511, Accuracy: 0.7851312160491943

In [39]:
# Export our model to HDF5 file
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/Starter_Code.h5')
files.download('/content/Starter_Code.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(